### ISSUE TITLE
Modificar jerarquias de active-force

### ISSUE THREAD

**Issue by emagarc** [tomasg88/bvlc#141]
Se debe revisar las nuevas jerarquías brindadas por Bomberos y actualizar los schemas de sanity, a su vez se debe permitir colocar el blasón correspondiente en el mismo div que contiene el título de jerarquía o en su defecto al lado de la imagen de cada una de las personas que integran dicha jerarquía. Esta segunda opción la considero menos conveniente al haber mas de una persona en cada una pero se puede considerar.

- [x] Lista online:
1.  Comandante General - Jefe de Cuerpo
2. Comandante -2do Jefe de cuerpo
3. Subcomandante
4. Oficial Inspector
5. Suboficial Primero
6. Sargento primero
7. Sargento
8. Cabo Primero
9. Cabo
10. Bombero
11. Aspirante

- [x] Lista de rangos actualizada:
1. Comandante General
2. Comandante Mayor (NUEVO RANGO)
3. Comandante 
4. Subcomandante
5. Oficial principal (NUEVO RANGO)
6. Oficial Inspector
7. Oficial ayudante (NUEVO RANGO)
8. Suboficial Mayor (NUEVO RANGO)
9. Suboficial Principal (NUEVO RANGO)
10. Sargento Primero
11. Sargento
12. Cabo Primero
13. Cabo
14. Bombero (En lista original pero no en la nueva)
15. Aspirante (En lista original pero no en la nueva)

**Comment by tomasg88** [comment]
@tomasg88 confirmar con Carlos cuál sería el cambio porque esas jerarquías ya existen.

**Comment by tomasg88** [comment]
Carlos nos tiene que confirmar. Vuelvo el ticket TO-DO

**Comment by tomasg88** [comment]
Los rangos nuevos, que deben estar arriba de todo, son:
* Jefe de Cuerpo
* 2do Jefe de Cuerpo

Ambos rangos hoy en día están hardcodeados en el código, y en realidad deben quedar primero que todos:
1. Jefe de Cuerpo
2. 2do Jefe de Cuerpo
3. Comandante General
4. Comandante
5. Subcomandante
6. etc.

Además, eliminar el texto que está hardcodeado en el sitio en la página `cuerpo-activo.tsx`

**Comment by tomasg88** [comment]
Mergeado a `main`
